package me.hvmarci.bedwars.ItemDeclarations;

public enum ItemType {
	GYAPJU, DESZKA, ENDKO, OBSZIDIAN, FAKARD, KOKARD, VASKARD, GYEMANTKARD, NETHERITKARD, NETHERITFEJSZE, TOLGYCSEMETE,
	FOLD, VILLAMPALCA
}
